### ISSUE TITLE
Image upload in Firefox(Mac) and bugs in image effects module selecting via addStep 

### ISSUE THREAD

**Issue by rackstar17** [publiclab/image-sequencer#7]
1. When I upload an image in Firefox (Mac) Image does not upload and I get this issue in the console 

<img width="1280" alt="image-upload" src="https://cloud.githubusercontent.com/assets/7199228/23766216/e4e94782-0529-11e7-8ec3-d62c4aa9bac5.png">

2. No module works when I select it from the select dropdown and then click on add step , I get the following issue on the console

<img width="1280" alt="green-channel-issue" src="https://cloud.githubusercontent.com/assets/7199228/23766254/0a966262-052a-11e7-81de-8104b17cdbf2.png">

I tested it in dev mode, not on the github hosted versions

**Comment by ccpandhare** [comment]
I have fixed this issue in my PR.
It hasn't been merged yet See Issue #2 , PR #6

**Comment by rackstar17** [comment]
PR #6 does not fix the problems mentioned above 
Uncaught error still shows up when image is uploaded not dragged

**Comment by ccpandhare** [comment]
Yeah I saw that. Sorry I hadn't tested that on Mac.
I've fixed that in PR #12

**Comment by jywarren** [comment]
Awesome troubleshooting folks, thanks!

**Comment by ccpandhare** [comment]
I think this issue isn't needed anymore.
